export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const ADD_DATA_REQUEST = "ADD_DATA_REQUEST";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_FAILURE = "ADD_DATA_FAILURE";

export const DELETE_DATA_REQUEST = "ADD_DATA_REQUEST";
export const DELETE_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const DELETE_DATA_FAILURE = "ADD_DATA_FAILURE";

export const UPDATE_DATA_REQUEST = "ADD_DATA_REQUEST";
export const UPDATE_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const UPDATE_DATA_FAILURE = "ADD_DATA_FAILURE";
